version: '3'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./config:/app/config
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80